M48
; DRILL file {KiCad 9.0.0} date 2025-03-19T11:42:45+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-19T11:42:45+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X156.5Y-93.5
X161.5Y-99.5
T2
X136.2Y-73.42
X179.0Y-73.5
M30
